# dyne:bolic master environment
# this file gets executed every time a zsh is opened

# common environment
source /etc/zsh/common 2>/dev/null 1>/dev/null

# boot modes
if [ -r /tmp/dyne ]; then
  source /etc/zsh/dyne
elif [ -r /tmp/ascii ]; then
  source /etc/zsh/ascii
else
  source /etc/zsh/volatile
fi

# dyne modules paths
source /etc/zsh/modules

# generated at boot
source /boot/dynenv

# after this, /home/.zshrc gets sourced
# edit your own there, don't touch this.

