# dyne:bolic master environment
# this file gets executed every time a zsh is opened

# dyne environment
source /lib/dyne/zsh/env

# after this, /home/.zshrc gets sourced
# edit your own there, don't touch this.

