/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_win_main (void)
{
  GtkWidget *win_main;
  GtkWidget *vbox1;
  GtkWidget *table1;
  GtkWidget *vbox2;
  GtkWidget *label_lang;
  GtkWidget *combo1;
  GtkWidget *combo_lang;
  GtkWidget *vbox3;
  GtkWidget *label_keyb;
  GtkWidget *combo2;
  GtkWidget *combo_keyb;
  GtkWidget *pixmap1;
  GtkWidget *pixmap2;
  GtkWidget *hbuttonbox1;
  guint button_ok_key;
  GtkWidget *button_ok;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  win_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_main, "win_main");
  gtk_object_set_data (GTK_OBJECT (win_main), "win_main", win_main);
  gtk_window_set_title (GTK_WINDOW (win_main), _("dyne:bolic :: lost in babylon"));
  gtk_window_set_position (GTK_WINDOW (win_main), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (win_main), FALSE, FALSE, FALSE);
  gtk_window_set_wmclass (GTK_WINDOW (win_main), "babylon", "dynebolic");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (win_main), vbox1);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 5);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_table_attach (GTK_TABLE (table1), vbox2, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 10);

  label_lang = gtk_label_new (_("Choose your language:"));
  gtk_widget_set_name (label_lang, "label_lang");
  gtk_widget_ref (label_lang);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "label_lang", label_lang,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_lang);
  gtk_box_pack_start (GTK_BOX (vbox2), label_lang, FALSE, FALSE, 0);

  combo1 = gtk_combo_new ();
  gtk_widget_set_name (combo1, "combo1");
  gtk_widget_ref (combo1);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "combo1", combo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo1);
  gtk_box_pack_start (GTK_BOX (vbox2), combo1, FALSE, FALSE, 0);

  combo_lang = GTK_COMBO (combo1)->entry;
  gtk_widget_set_name (combo_lang, "combo_lang");
  gtk_widget_ref (combo_lang);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "combo_lang", combo_lang,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_lang);
  gtk_entry_set_editable (GTK_ENTRY (combo_lang), FALSE);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_table_attach (GTK_TABLE (table1), vbox3, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 10);

  label_keyb = gtk_label_new (_("Choose your keyboard layout:"));
  gtk_widget_set_name (label_keyb, "label_keyb");
  gtk_widget_ref (label_keyb);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "label_keyb", label_keyb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_keyb);
  gtk_box_pack_start (GTK_BOX (vbox3), label_keyb, FALSE, FALSE, 0);

  combo2 = gtk_combo_new ();
  gtk_widget_set_name (combo2, "combo2");
  gtk_widget_ref (combo2);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "combo2", combo2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo2);
  gtk_box_pack_start (GTK_BOX (vbox3), combo2, FALSE, FALSE, 0);

  combo_keyb = GTK_COMBO (combo2)->entry;
  gtk_widget_set_name (combo_keyb, "combo_keyb");
  gtk_widget_ref (combo_keyb);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "combo_keyb", combo_keyb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_keyb);
  gtk_entry_set_editable (GTK_ENTRY (combo_keyb), FALSE);

  pixmap1 = create_pixmap (win_main, "locale.xpm");
  gtk_widget_set_name (pixmap1, "pixmap1");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_table_attach (GTK_TABLE (table1), pixmap1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  pixmap2 = create_pixmap (win_main, "charselect.xpm");
  gtk_widget_set_name (pixmap2, "pixmap2");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_table_attach (GTK_TABLE (table1), pixmap2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, FALSE, 0);

  button_ok = gtk_button_new_with_label ("");
  button_ok_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (button_ok)->child),
                                   _("_Ok"));
  gtk_widget_add_accelerator (button_ok, "clicked", accel_group,
                              button_ok_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (button_ok, "button_ok");
  gtk_widget_ref (button_ok);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "button_ok", button_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_ok);
  gtk_container_set_border_width (GTK_CONTAINER (button_ok), 3);
  GTK_WIDGET_SET_FLAGS (button_ok, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (win_main), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (combo1), "realize",
                      GTK_SIGNAL_FUNC (on_combo1_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (combo_lang), "changed",
                      GTK_SIGNAL_FUNC (on_combo_lang_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (combo2), "realize",
                      GTK_SIGNAL_FUNC (on_combo2_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (combo_keyb), "changed",
                      GTK_SIGNAL_FUNC (on_combo_keyb_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_ok), "released",
                      GTK_SIGNAL_FUNC (on_button_ok_released),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (win_main), accel_group);

  return win_main;
}

