#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

log_begin_msg "Regenerating SSL certificate..."

# live-initramfs script

if [ -x /root/usr/sbin/make-ssl-cert ]
then
	chroot /root /usr/sbin/make-ssl-cert generate-default-snakeoil --force-overwrite
fi

log_end_msg
