/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_win_select (void)
{
  GtkWidget *win_select;
  GtkWidget *mainframe;
  GtkWidget *vbox1;
  GtkWidget *label_intro;
  GtkWidget *vbox2;
  GtkWidget *frame_hd;
  GtkWidget *hbox1;
  GtkWidget *label_hd;
  GtkWidget *pix_hd;
  GSList *nest_sel_group = NULL;
  GtkWidget *radio_hd;
  GtkWidget *frame_usb;
  GtkWidget *hbox2;
  GtkWidget *label_usb;
  GtkWidget *pix_usb;
  GtkWidget *radio_usb;
  GtkWidget *frame3;
  GtkWidget *hbox3;
  GtkWidget *label3;
  GtkWidget *pix_floppy;
  GtkWidget *radio_floppy;
  GtkWidget *button1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_select = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (win_select), "win_select", win_select);
  gtk_window_set_title (GTK_WINDOW (win_select), _("taschino :: nest your dyne:bolic"));
  gtk_window_set_position (GTK_WINDOW (win_select), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (win_select), FALSE, FALSE, FALSE);
  gtk_window_set_wmclass (GTK_WINDOW (win_select), "taschino", "dynebolic");

  mainframe = gtk_frame_new (_("Nest dyne:bolic "));
  gtk_widget_ref (mainframe);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "mainframe", mainframe,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mainframe);
  gtk_container_add (GTK_CONTAINER (win_select), mainframe);
  gtk_container_set_border_width (GTK_CONTAINER (mainframe), 5);
  gtk_frame_set_shadow_type (GTK_FRAME (mainframe), GTK_SHADOW_OUT);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainframe), vbox1);

  label_intro = gtk_label_new (_("With nesting you have 3 possibilities to save your data and settings: dyne:bolic can nest on different media and in different ways, then detects the nest and activates it at every boot."));
  gtk_widget_ref (label_intro);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "label_intro", label_intro,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_intro);
  gtk_box_pack_start (GTK_BOX (vbox1), label_intro, FALSE, FALSE, 0);
  gtk_widget_set_usize (label_intro, 435, -2);
  gtk_label_set_justify (GTK_LABEL (label_intro), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label_intro), TRUE);
  gtk_misc_set_padding (GTK_MISC (label_intro), 3, 3);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 10);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 5);

  frame_hd = gtk_frame_new (_("Nest on harddisk"));
  gtk_widget_ref (frame_hd);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "frame_hd", frame_hd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_hd);
  gtk_box_pack_start (GTK_BOX (vbox2), frame_hd, TRUE, TRUE, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame_hd), 1, 0.5);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (frame_hd), hbox1);

  label_hd = gtk_label_new (_("Nest your /home and all your settings, the nest can be password secured with encryption and doesn't needs repartitioning, to keep your data you just use 64Mb or more by creating one simple file: the .dynebolic.nest"));
  gtk_widget_ref (label_hd);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "label_hd", label_hd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_hd);
  gtk_box_pack_start (GTK_BOX (hbox1), label_hd, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_hd), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label_hd), TRUE);
  gtk_misc_set_padding (GTK_MISC (label_hd), 3, 0);

  pix_hd = create_pixmap (win_select, "harddisk.xpm");
  gtk_widget_ref (pix_hd);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "pix_hd", pix_hd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pix_hd);
  gtk_box_pack_start (GTK_BOX (hbox1), pix_hd, TRUE, TRUE, 0);

  radio_hd = gtk_radio_button_new_with_label (nest_sel_group, "");
  nest_sel_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radio_hd));
  gtk_widget_ref (radio_hd);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "radio_hd", radio_hd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radio_hd);
  gtk_box_pack_start (GTK_BOX (hbox1), radio_hd, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (radio_hd), 5);
  GTK_WIDGET_UNSET_FLAGS (radio_hd, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, radio_hd, _("select nesting on harddisk"), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radio_hd), TRUE);

  frame_usb = gtk_frame_new (_("Nest on usb pen "));
  gtk_widget_ref (frame_usb);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "frame_usb", frame_usb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_usb);
  gtk_box_pack_start (GTK_BOX (vbox2), frame_usb, TRUE, TRUE, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame_usb), 1, 0.5);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (frame_usb), hbox2);

  label_usb = gtk_label_new (_("Nest your /home and all your settings, it will place your /home directory and other settings in your usb pen filesystem and you'll be able to access them also from outside dyne:bolic system"));
  gtk_widget_ref (label_usb);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "label_usb", label_usb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_usb);
  gtk_box_pack_start (GTK_BOX (hbox2), label_usb, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_usb), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label_usb), TRUE);
  gtk_misc_set_padding (GTK_MISC (label_usb), 3, 0);

  pix_usb = create_pixmap (win_select, "dongle.xpm");
  gtk_widget_ref (pix_usb);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "pix_usb", pix_usb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pix_usb);
  gtk_box_pack_start (GTK_BOX (hbox2), pix_usb, TRUE, TRUE, 0);

  radio_usb = gtk_radio_button_new_with_label (nest_sel_group, "");
  nest_sel_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radio_usb));
  gtk_widget_ref (radio_usb);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "radio_usb", radio_usb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radio_usb);
  gtk_box_pack_start (GTK_BOX (hbox2), radio_usb, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (radio_usb), 5);
  GTK_WIDGET_UNSET_FLAGS (radio_usb, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, radio_usb, _("select nesting on usb pen"), NULL);

  frame3 = gtk_frame_new (_("Nest on floppy"));
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox2), frame3, TRUE, TRUE, 0);
  gtk_frame_set_label_align (GTK_FRAME (frame3), 1, 0.5);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (frame3), hbox3);

  label3 = gtk_label_new (_("Nest your mail, bookmarks and encryption settings, reformatting your floppy with a compressed filesystem to fit in more space"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label3), TRUE);
  gtk_misc_set_padding (GTK_MISC (label3), 3, 0);

  pix_floppy = create_pixmap (win_select, "floppy.xpm");
  gtk_widget_ref (pix_floppy);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "pix_floppy", pix_floppy,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pix_floppy);
  gtk_box_pack_start (GTK_BOX (hbox3), pix_floppy, TRUE, TRUE, 0);

  radio_floppy = gtk_radio_button_new_with_label (nest_sel_group, "");
  nest_sel_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radio_floppy));
  gtk_widget_ref (radio_floppy);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "radio_floppy", radio_floppy,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radio_floppy);
  gtk_box_pack_start (GTK_BOX (hbox3), radio_floppy, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (radio_floppy), 5);
  GTK_WIDGET_UNSET_FLAGS (radio_floppy, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, radio_floppy, _("select nesting on floppy"), NULL);

  button1 = gtk_button_new_with_label (_("- O K -"));
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (win_select), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (vbox2), button1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button1), 5);

  gtk_signal_connect (GTK_OBJECT (win_select), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button1), "released",
                      GTK_SIGNAL_FUNC (on_nest_selection_released),
                      nest_sel_group);
  gtk_signal_connect (GTK_OBJECT (button1), "pressed",
                      GTK_SIGNAL_FUNC (on_nest_selection_pressed),
                      win_select);

  gtk_object_set_data (GTK_OBJECT (win_select), "tooltips", tooltips);

  return win_select;
}

GtkWidget*
create_win_nest_hd (void)
{
  GtkWidget *win_nest_hd;
  GtkWidget *frame_nest_hd;
  GtkWidget *vbox3;
  GtkWidget *hbox4;
  GtkWidget *vbox4;
  GtkWidget *label_hd_select;
  GtkWidget *combo_part;
  GtkWidget *combo_hd_partitions;
  GtkWidget *pixmap6;
  GtkWidget *label_hd_size;
  GtkWidget *hscale_hd_megabytes;
  GtkWidget *hbox5;
  GtkWidget *toggle_pass_hd;
  GtkWidget *label4;
  GtkWidget *hbuttonbox1;
  GtkWidget *cancel_nest_hd;
  GtkWidget *ok_nest_hd;

  win_nest_hd = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (win_nest_hd), "win_nest_hd", win_nest_hd);
  gtk_window_set_title (GTK_WINDOW (win_nest_hd), _("taschino :: nest on harddisk"));
  gtk_window_set_position (GTK_WINDOW (win_nest_hd), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (win_nest_hd), FALSE, FALSE, FALSE);
  gtk_window_set_wmclass (GTK_WINDOW (win_nest_hd), "taschino", "dynebolic");

  frame_nest_hd = gtk_frame_new (_("Nest dyne:bolic on harddisk"));
  gtk_widget_ref (frame_nest_hd);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "frame_nest_hd", frame_nest_hd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_nest_hd);
  gtk_container_add (GTK_CONTAINER (win_nest_hd), frame_nest_hd);
  gtk_container_set_border_width (GTK_CONTAINER (frame_nest_hd), 3);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (frame_nest_hd), vbox3);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox4, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox4), 5);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox4, TRUE, TRUE, 0);

  label_hd_select = gtk_label_new (_("Select the harddisk partition where you want to create the dyne:bolic nest"));
  gtk_widget_ref (label_hd_select);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "label_hd_select", label_hd_select,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_hd_select);
  gtk_box_pack_start (GTK_BOX (vbox4), label_hd_select, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_hd_select), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label_hd_select), TRUE);
  gtk_misc_set_padding (GTK_MISC (label_hd_select), 0, 15);

  combo_part = gtk_combo_new ();
  gtk_widget_ref (combo_part);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "combo_part", combo_part,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_part);
  gtk_box_pack_start (GTK_BOX (vbox4), combo_part, FALSE, FALSE, 0);

  combo_hd_partitions = GTK_COMBO (combo_part)->entry;
  gtk_widget_ref (combo_hd_partitions);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "combo_hd_partitions", combo_hd_partitions,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_hd_partitions);
  GTK_WIDGET_UNSET_FLAGS (combo_hd_partitions, GTK_CAN_FOCUS);
  gtk_entry_set_editable (GTK_ENTRY (combo_hd_partitions), FALSE);
  gtk_entry_set_text (GTK_ENTRY (combo_hd_partitions), _("no harddisk found"));

  pixmap6 = create_pixmap (win_nest_hd, "harddisk.xpm");
  gtk_widget_ref (pixmap6);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "pixmap6", pixmap6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap6);
  gtk_box_pack_start (GTK_BOX (hbox4), pixmap6, FALSE, FALSE, 0);

  label_hd_size = gtk_label_new (_("How many MEGABYTES you want to occupy with your nest?"));
  gtk_widget_ref (label_hd_size);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "label_hd_size", label_hd_size,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_hd_size);
  gtk_box_pack_start (GTK_BOX (vbox3), label_hd_size, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label_hd_size), 0, 4);

  hscale_hd_megabytes = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (64, 64, 1500, 1, 0, 0)));
  gtk_widget_ref (hscale_hd_megabytes);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "hscale_hd_megabytes", hscale_hd_megabytes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hscale_hd_megabytes);
  gtk_box_pack_start (GTK_BOX (vbox3), hscale_hd_megabytes, FALSE, FALSE, 0);
  gtk_scale_set_digits (GTK_SCALE (hscale_hd_megabytes), 0);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox5, TRUE, TRUE, 0);

  toggle_pass_hd = gtk_toggle_button_new_with_label (_(" secure with \n password and \n encryption "));
  gtk_widget_ref (toggle_pass_hd);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "toggle_pass_hd", toggle_pass_hd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toggle_pass_hd);
  gtk_box_pack_start (GTK_BOX (hbox5), toggle_pass_hd, FALSE, FALSE, 3);
  gtk_container_set_border_width (GTK_CONTAINER (toggle_pass_hd), 5);

  label4 = gtk_label_new (_("By securing with password you will generate an encrypted (AES128) nest and you'll be prompted for the passphrase at every boot."));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox5), label4, FALSE, FALSE, 10);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label4), TRUE);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), hbuttonbox1, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_SPREAD);

  cancel_nest_hd = gtk_button_new_with_label (_("Abort"));
  gtk_widget_ref (cancel_nest_hd);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "cancel_nest_hd", cancel_nest_hd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cancel_nest_hd);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), cancel_nest_hd);
  GTK_WIDGET_SET_FLAGS (cancel_nest_hd, GTK_CAN_DEFAULT);

  ok_nest_hd = gtk_button_new_with_label (_("Ok, NEST !"));
  gtk_widget_ref (ok_nest_hd);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_hd), "ok_nest_hd", ok_nest_hd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ok_nest_hd);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), ok_nest_hd);
  GTK_WIDGET_SET_FLAGS (ok_nest_hd, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (win_nest_hd), "destroy",
                      GTK_SIGNAL_FUNC (on_win_nest_hd_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (combo_part), "realize",
                      GTK_SIGNAL_FUNC (on_combo1_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (combo_hd_partitions), "changed",
                      GTK_SIGNAL_FUNC (on_combo_hd_partitions_changed),
                      hscale_hd_megabytes);
  gtk_signal_connect (GTK_OBJECT (toggle_pass_hd), "toggled",
                      GTK_SIGNAL_FUNC (on_toggle_pass_hd_toggled),
                      NULL);
  gtk_signal_connect_object (GTK_OBJECT (cancel_nest_hd), "released",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (win_nest_hd));
  gtk_signal_connect (GTK_OBJECT (ok_nest_hd), "released",
                      GTK_SIGNAL_FUNC (on_ok_nest_hd_released),
                      hscale_hd_megabytes);

  return win_nest_hd;
}

GtkWidget*
create_win_nest_usb (void)
{
  GtkWidget *win_nest_usb;
  GtkWidget *frame_nest_usb;
  GtkWidget *vbox_usb_3;
  GtkWidget *hbox_usb_4;
  GtkWidget *vbox_usb_4;
  GtkWidget *label_usb_select;
  GtkWidget *combo_usb_part;
  GtkWidget *combo_usb_partitions;
  GtkWidget *pixmap_usb_6;
  GtkWidget *label_usb_size;
  GtkWidget *hscale_usb_megabytes;
  GtkWidget *hbox_usb_5;
  GtkWidget *toggle_pass_usb;
  GtkWidget *label_usb_4;
  GtkWidget *hbuttonbox_usb_1;
  GtkWidget *cancel_nest_usb;
  GtkWidget *ok_nest_usb;

  win_nest_usb = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (win_nest_usb), "win_nest_usb", win_nest_usb);
  gtk_window_set_title (GTK_WINDOW (win_nest_usb), _("taschino :: nest on usb storage"));
  gtk_window_set_position (GTK_WINDOW (win_nest_usb), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (win_nest_usb), FALSE, FALSE, FALSE);
  gtk_window_set_wmclass (GTK_WINDOW (win_nest_usb), "taschino", "dynebolic");

  frame_nest_usb = gtk_frame_new (_("Nest dyne:bolic on usb storage"));
  gtk_widget_ref (frame_nest_usb);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "frame_nest_usb", frame_nest_usb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_nest_usb);
  gtk_container_add (GTK_CONTAINER (win_nest_usb), frame_nest_usb);
  gtk_container_set_border_width (GTK_CONTAINER (frame_nest_usb), 3);

  vbox_usb_3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox_usb_3);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "vbox_usb_3", vbox_usb_3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox_usb_3);
  gtk_container_add (GTK_CONTAINER (frame_nest_usb), vbox_usb_3);

  hbox_usb_4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox_usb_4);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "hbox_usb_4", hbox_usb_4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox_usb_4);
  gtk_box_pack_start (GTK_BOX (vbox_usb_3), hbox_usb_4, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox_usb_4), 5);

  vbox_usb_4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox_usb_4);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "vbox_usb_4", vbox_usb_4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox_usb_4);
  gtk_box_pack_start (GTK_BOX (hbox_usb_4), vbox_usb_4, TRUE, TRUE, 0);

  label_usb_select = gtk_label_new (_("Select the usb partition where you want to create the dyne:bolic nest"));
  gtk_widget_ref (label_usb_select);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "label_usb_select", label_usb_select,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_usb_select);
  gtk_box_pack_start (GTK_BOX (vbox_usb_4), label_usb_select, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_usb_select), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label_usb_select), TRUE);
  gtk_misc_set_padding (GTK_MISC (label_usb_select), 0, 15);

  combo_usb_part = gtk_combo_new ();
  gtk_widget_ref (combo_usb_part);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "combo_usb_part", combo_usb_part,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_usb_part);
  gtk_box_pack_start (GTK_BOX (vbox_usb_4), combo_usb_part, FALSE, FALSE, 0);

  combo_usb_partitions = GTK_COMBO (combo_usb_part)->entry;
  gtk_widget_ref (combo_usb_partitions);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "combo_usb_partitions", combo_usb_partitions,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_usb_partitions);
  GTK_WIDGET_UNSET_FLAGS (combo_usb_partitions, GTK_CAN_FOCUS);
  gtk_entry_set_editable (GTK_ENTRY (combo_usb_partitions), FALSE);
  gtk_entry_set_text (GTK_ENTRY (combo_usb_partitions), _("no usb key found"));

  pixmap_usb_6 = create_pixmap (win_nest_usb, "dongle.xpm");
  gtk_widget_ref (pixmap_usb_6);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "pixmap_usb_6", pixmap_usb_6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap_usb_6);
  gtk_box_pack_start (GTK_BOX (hbox_usb_4), pixmap_usb_6, FALSE, FALSE, 0);

  label_usb_size = gtk_label_new (_("How many MEGABYTES you want to occupy with your nest?"));
  gtk_widget_ref (label_usb_size);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "label_usb_size", label_usb_size,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_usb_size);
  gtk_box_pack_start (GTK_BOX (vbox_usb_3), label_usb_size, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label_usb_size), 0, 4);

  hscale_usb_megabytes = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (64, 64, 1500, 1, 0, 0)));
  gtk_widget_ref (hscale_usb_megabytes);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "hscale_usb_megabytes", hscale_usb_megabytes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hscale_usb_megabytes);
  gtk_box_pack_start (GTK_BOX (vbox_usb_3), hscale_usb_megabytes, FALSE, FALSE, 0);
  gtk_scale_set_digits (GTK_SCALE (hscale_usb_megabytes), 0);

  hbox_usb_5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox_usb_5);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "hbox_usb_5", hbox_usb_5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox_usb_5);
  gtk_box_pack_start (GTK_BOX (vbox_usb_3), hbox_usb_5, TRUE, TRUE, 0);

  toggle_pass_usb = gtk_toggle_button_new_with_label (_(" secure with \n password and \n encryption "));
  gtk_widget_ref (toggle_pass_usb);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "toggle_pass_usb", toggle_pass_usb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toggle_pass_usb);
  gtk_box_pack_start (GTK_BOX (hbox_usb_5), toggle_pass_usb, FALSE, FALSE, 3);
  gtk_container_set_border_width (GTK_CONTAINER (toggle_pass_usb), 5);

  label_usb_4 = gtk_label_new (_("By securing with password you will generate an encrypted (AES128) nest and you'll be prompted for the passphrase at every boot."));
  gtk_widget_ref (label_usb_4);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "label_usb_4", label_usb_4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_usb_4);
  gtk_box_pack_start (GTK_BOX (hbox_usb_5), label_usb_4, FALSE, FALSE, 10);
  gtk_label_set_justify (GTK_LABEL (label_usb_4), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label_usb_4), TRUE);

  hbuttonbox_usb_1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox_usb_1);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "hbuttonbox_usb_1", hbuttonbox_usb_1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox_usb_1);
  gtk_box_pack_start (GTK_BOX (vbox_usb_3), hbuttonbox_usb_1, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox_usb_1), GTK_BUTTONBOX_SPREAD);

  cancel_nest_usb = gtk_button_new_with_label (_("Abort"));
  gtk_widget_ref (cancel_nest_usb);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "cancel_nest_usb", cancel_nest_usb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cancel_nest_usb);
  gtk_container_add (GTK_CONTAINER (hbuttonbox_usb_1), cancel_nest_usb);
  GTK_WIDGET_SET_FLAGS (cancel_nest_usb, GTK_CAN_DEFAULT);

  ok_nest_usb = gtk_button_new_with_label (_("Ok, NEST !"));
  gtk_widget_ref (ok_nest_usb);
  gtk_object_set_data_full (GTK_OBJECT (win_nest_usb), "ok_nest_usb", ok_nest_usb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ok_nest_usb);
  gtk_container_add (GTK_CONTAINER (hbuttonbox_usb_1), ok_nest_usb);
  GTK_WIDGET_SET_FLAGS (ok_nest_usb, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (win_nest_usb), "destroy",
                      GTK_SIGNAL_FUNC (on_win_nest_usb_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (combo_usb_part), "realize",
                      GTK_SIGNAL_FUNC (on_combo_usb_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (combo_usb_partitions), "changed",
                      GTK_SIGNAL_FUNC (on_combo_usb_partitions_changed),
                      hscale_usb_megabytes);
  gtk_signal_connect (GTK_OBJECT (toggle_pass_usb), "toggled",
                      GTK_SIGNAL_FUNC (on_toggle_pass_usb_toggled),
                      NULL);
  gtk_signal_connect_object (GTK_OBJECT (cancel_nest_usb), "released",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (win_nest_usb));
  gtk_signal_connect (GTK_OBJECT (ok_nest_usb), "released",
                      GTK_SIGNAL_FUNC (on_ok_nest_usb_released),
                      hscale_usb_megabytes);

  return win_nest_usb;
}

GtkWidget*
create_win_success (void)
{
  GtkWidget *win_success;
  GtkWidget *vbox5;
  GtkWidget *hbox6;
  GtkWidget *success_text;
  GtkWidget *pixmap_dynetux;
  GtkWidget *hbuttonbox2;
  GtkWidget *button_success;

  win_success = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (win_success), "win_success", win_success);
  gtk_container_set_border_width (GTK_CONTAINER (win_success), 3);
  gtk_window_set_title (GTK_WINDOW (win_success), _("taschino :: nest succesfully built"));
  gtk_window_set_position (GTK_WINDOW (win_success), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (win_success), FALSE, FALSE, FALSE);
  gtk_window_set_wmclass (GTK_WINDOW (win_success), "taschino", "dynebolic");

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (win_success), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (win_success), vbox5);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (win_success), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox6, TRUE, TRUE, 0);

  success_text = gtk_label_new (_("Success! your dyne:bolic nest has been succesfully created, you'll find back your settings at every boot starting from now!"));
  gtk_widget_ref (success_text);
  gtk_object_set_data_full (GTK_OBJECT (win_success), "success_text", success_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (success_text);
  gtk_box_pack_start (GTK_BOX (hbox6), success_text, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (success_text), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (success_text), TRUE);
  gtk_misc_set_padding (GTK_MISC (success_text), 10, 0);

  pixmap_dynetux = create_pixmap (win_success, "dynetux.xpm");
  gtk_widget_ref (pixmap_dynetux);
  gtk_object_set_data_full (GTK_OBJECT (win_success), "pixmap_dynetux", pixmap_dynetux,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap_dynetux);
  gtk_box_pack_start (GTK_BOX (hbox6), pixmap_dynetux, TRUE, TRUE, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (win_success), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox5), hbuttonbox2, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_SPREAD);

  button_success = gtk_button_new_with_label (_("I feel GOOD!"));
  gtk_widget_ref (button_success);
  gtk_object_set_data_full (GTK_OBJECT (win_success), "button_success", button_success,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_success);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button_success);
  gtk_container_set_border_width (GTK_CONTAINER (button_success), 5);
  GTK_WIDGET_UNSET_FLAGS (button_success, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (button_success, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (win_success), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_success), "released",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);

  return win_success;
}

GtkWidget*
create_win_not_found (void)
{
  GtkWidget *win_not_found;
  GtkWidget *vbox6;
  GtkWidget *hbox7;
  GtkWidget *not_found_text;
  GtkWidget *pixmap8;
  GtkWidget *hbuttonbox3;
  GtkWidget *button_abort_not_present;
  GtkWidget *button_retry_not_present;

  win_not_found = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (win_not_found), "win_not_found", win_not_found);
  gtk_window_set_title (GTK_WINDOW (win_not_found), _("taschino :: media not found"));
  gtk_window_set_position (GTK_WINDOW (win_not_found), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (win_not_found), FALSE, FALSE, FALSE);
  gtk_window_set_wmclass (GTK_WINDOW (win_not_found), "taschino", "dynebolic");

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (win_not_found), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (win_not_found), vbox6);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox7);
  gtk_object_set_data_full (GTK_OBJECT (win_not_found), "hbox7", hbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox7, TRUE, TRUE, 0);

  not_found_text = gtk_label_new (_("The media you selected for you nest has not been found (or a nest is allready there).\nPlease insert a floppy or usb-key, or make sure an harddisk is present in your computer. "));
  gtk_widget_ref (not_found_text);
  gtk_object_set_data_full (GTK_OBJECT (win_not_found), "not_found_text", not_found_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (not_found_text);
  gtk_box_pack_start (GTK_BOX (hbox7), not_found_text, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (not_found_text), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (not_found_text), TRUE);
  gtk_misc_set_padding (GTK_MISC (not_found_text), 10, 0);

  pixmap8 = create_pixmap (win_not_found, "penguhangry.xpm");
  gtk_widget_ref (pixmap8);
  gtk_object_set_data_full (GTK_OBJECT (win_not_found), "pixmap8", pixmap8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap8);
  gtk_box_pack_start (GTK_BOX (hbox7), pixmap8, TRUE, TRUE, 0);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (win_not_found), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox6), hbuttonbox3, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_SPREAD);

  button_abort_not_present = gtk_button_new_with_label (_("Abort"));
  gtk_widget_ref (button_abort_not_present);
  gtk_object_set_data_full (GTK_OBJECT (win_not_found), "button_abort_not_present", button_abort_not_present,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_abort_not_present);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button_abort_not_present);
  gtk_container_set_border_width (GTK_CONTAINER (button_abort_not_present), 3);
  GTK_WIDGET_UNSET_FLAGS (button_abort_not_present, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (button_abort_not_present, GTK_CAN_DEFAULT);

  button_retry_not_present = gtk_button_new_with_label (_("Retry!"));
  gtk_widget_ref (button_retry_not_present);
  gtk_object_set_data_full (GTK_OBJECT (win_not_found), "button_retry_not_present", button_retry_not_present,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_retry_not_present);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button_retry_not_present);
  gtk_container_set_border_width (GTK_CONTAINER (button_retry_not_present), 3);
  GTK_WIDGET_UNSET_FLAGS (button_retry_not_present, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (button_retry_not_present, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (win_not_found), "destroy",
                      GTK_SIGNAL_FUNC (on_win_not_found_destroy),
                      NULL);
  gtk_signal_connect_object (GTK_OBJECT (button_abort_not_present), "released",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (win_not_found));
  gtk_signal_connect (GTK_OBJECT (button_retry_not_present), "released",
                      GTK_SIGNAL_FUNC (on_button_retry_not_present_released),
                      NULL);

  return win_not_found;
}

GtkWidget*
create_win_failure (void)
{
  GtkWidget *win_failure;
  GtkWidget *vbox7;
  GtkWidget *hbox8;
  GtkWidget *label5;
  GtkWidget *pixmap9;
  GtkWidget *hbuttonbox4;
  GtkWidget *button_gosh;

  win_failure = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (win_failure), "win_failure", win_failure);
  gtk_window_set_title (GTK_WINDOW (win_failure), _("taschino :: nesting failed :("));
  gtk_window_set_position (GTK_WINDOW (win_failure), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (win_failure), FALSE, FALSE, FALSE);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (win_failure), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (win_failure), vbox7);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox8);
  gtk_object_set_data_full (GTK_OBJECT (win_failure), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox8, TRUE, TRUE, 0);

  label5 = gtk_label_new (_("Some PROBLEM arised during the nesting process, the operation was ABORTED, nothing has been modified on yuor media.\nsee the LOG in /var/log/setup/nidifica.log"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (win_failure), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox8), label5, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label5), TRUE);
  gtk_misc_set_padding (GTK_MISC (label5), 10, 0);

  pixmap9 = create_pixmap (win_failure, "pengudown.xpm");
  gtk_widget_ref (pixmap9);
  gtk_object_set_data_full (GTK_OBJECT (win_failure), "pixmap9", pixmap9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap9);
  gtk_box_pack_start (GTK_BOX (hbox8), pixmap9, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (pixmap9), 0, 5);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox4);
  gtk_object_set_data_full (GTK_OBJECT (win_failure), "hbuttonbox4", hbuttonbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (vbox7), hbuttonbox4, TRUE, TRUE, 0);

  button_gosh = gtk_button_new_with_label (_("GOSH!"));
  gtk_widget_ref (button_gosh);
  gtk_object_set_data_full (GTK_OBJECT (win_failure), "button_gosh", button_gosh,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_gosh);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button_gosh);
  gtk_container_set_border_width (GTK_CONTAINER (button_gosh), 5);
  GTK_WIDGET_UNSET_FLAGS (button_gosh, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (button_gosh, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (win_failure), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_gosh), "released",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);

  return win_failure;
}

GtkWidget*
create_win_has_nest (void)
{
  GtkWidget *win_has_nest;
  GtkWidget *vbox8;
  GtkWidget *hbox9;
  GtkWidget *label_has_nest;
  GtkWidget *logo_has_nest;
  GtkWidget *hbuttonbox5;
  GtkWidget *button_has_nest;

  win_has_nest = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (win_has_nest), "win_has_nest", win_has_nest);
  gtk_window_set_title (GTK_WINDOW (win_has_nest), _("taschino:: nest found on media"));
  gtk_window_set_policy (GTK_WINDOW (win_has_nest), FALSE, FALSE, FALSE);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (win_has_nest), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (win_has_nest), vbox8);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox9);
  gtk_object_set_data_full (GTK_OBJECT (win_has_nest), "hbox9", hbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox9, TRUE, TRUE, 0);

  label_has_nest = gtk_label_new (_("A nest is allready present on a scanned device, it is excluded from your nesting choices."));
  gtk_widget_ref (label_has_nest);
  gtk_object_set_data_full (GTK_OBJECT (win_has_nest), "label_has_nest", label_has_nest,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_has_nest);
  gtk_box_pack_start (GTK_BOX (hbox9), label_has_nest, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_has_nest), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label_has_nest), TRUE);
  gtk_misc_set_padding (GTK_MISC (label_has_nest), 10, 0);

  logo_has_nest = create_pixmap (win_has_nest, "logo.xpm");
  gtk_widget_ref (logo_has_nest);
  gtk_object_set_data_full (GTK_OBJECT (win_has_nest), "logo_has_nest", logo_has_nest,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (logo_has_nest);
  gtk_box_pack_start (GTK_BOX (hbox9), logo_has_nest, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (logo_has_nest), 0, 5);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox5);
  gtk_object_set_data_full (GTK_OBJECT (win_has_nest), "hbuttonbox5", hbuttonbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox5);
  gtk_box_pack_start (GTK_BOX (vbox8), hbuttonbox5, TRUE, TRUE, 0);

  button_has_nest = gtk_button_new_with_label (_("Ok, I know!"));
  gtk_widget_ref (button_has_nest);
  gtk_object_set_data_full (GTK_OBJECT (win_has_nest), "button_has_nest", button_has_nest,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_has_nest);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button_has_nest);
  gtk_container_set_border_width (GTK_CONTAINER (button_has_nest), 5);
  GTK_WIDGET_SET_FLAGS (button_has_nest, GTK_CAN_DEFAULT);

  gtk_signal_connect_object (GTK_OBJECT (button_has_nest), "released",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (win_has_nest));

  return win_has_nest;
}

GtkWidget*
create_notimplemented (void)
{
  GtkWidget *notimplemented;
  GtkWidget *vbox_notimpl_11;
  GtkWidget *hbox_notimpl_6;
  GtkWidget *frame_notimpl_8;
  GtkWidget *pixmap_notimpl_4;
  GtkWidget *label_notimpl_10;
  GtkWidget *iwait_notimpl;

  notimplemented = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_object_set_data (GTK_OBJECT (notimplemented), "notimplemented", notimplemented);
  gtk_container_set_border_width (GTK_CONTAINER (notimplemented), 2);
  gtk_window_set_title (GTK_WINDOW (notimplemented), _("We are working for you!"));
  gtk_window_set_position (GTK_WINDOW (notimplemented), GTK_WIN_POS_MOUSE);
  gtk_window_set_policy (GTK_WINDOW (notimplemented), FALSE, FALSE, TRUE);

  vbox_notimpl_11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox_notimpl_11);
  gtk_object_set_data_full (GTK_OBJECT (notimplemented), "vbox_notimpl_11", vbox_notimpl_11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox_notimpl_11);
  gtk_container_add (GTK_CONTAINER (notimplemented), vbox_notimpl_11);

  hbox_notimpl_6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox_notimpl_6);
  gtk_object_set_data_full (GTK_OBJECT (notimplemented), "hbox_notimpl_6", hbox_notimpl_6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox_notimpl_6);
  gtk_box_pack_start (GTK_BOX (vbox_notimpl_11), hbox_notimpl_6, TRUE, TRUE, 0);

  frame_notimpl_8 = gtk_frame_new (NULL);
  gtk_widget_ref (frame_notimpl_8);
  gtk_object_set_data_full (GTK_OBJECT (notimplemented), "frame_notimpl_8", frame_notimpl_8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_notimpl_8);
  gtk_box_pack_start (GTK_BOX (hbox_notimpl_6), frame_notimpl_8, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame_notimpl_8), 10);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_notimpl_8), GTK_SHADOW_NONE);

  pixmap_notimpl_4 = create_pixmap (notimplemented, "unimplemented.xpm");
  gtk_widget_ref (pixmap_notimpl_4);
  gtk_object_set_data_full (GTK_OBJECT (notimplemented), "pixmap_notimpl_4", pixmap_notimpl_4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap_notimpl_4);
  gtk_container_add (GTK_CONTAINER (frame_notimpl_8), pixmap_notimpl_4);

  label_notimpl_10 = gtk_label_new (_("This function is not\nyet implemented.\nPlease be patient\nwhile we are working\non it and keep an eye\non the next releases\nof dyne:bolic !"));
  gtk_widget_ref (label_notimpl_10);
  gtk_object_set_data_full (GTK_OBJECT (notimplemented), "label_notimpl_10", label_notimpl_10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_notimpl_10);
  gtk_box_pack_start (GTK_BOX (hbox_notimpl_6), label_notimpl_10, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_notimpl_10), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label_notimpl_10), 15, 0);

  iwait_notimpl = gtk_button_new_with_label (_("OK! keep up the good work!"));
  gtk_widget_ref (iwait_notimpl);
  gtk_object_set_data_full (GTK_OBJECT (notimplemented), "iwait_notimpl", iwait_notimpl,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (iwait_notimpl);
  gtk_box_pack_start (GTK_BOX (vbox_notimpl_11), iwait_notimpl, FALSE, FALSE, 2);

  gtk_signal_connect_object (GTK_OBJECT (iwait_notimpl), "released",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (notimplemented));

  return notimplemented;
}

