/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_win_select (void);
GtkWidget* create_win_nest_hd (void);
GtkWidget* create_win_success (void);
GtkWidget* create_win_not_found (void);
GtkWidget* create_win_failure (void);
GtkWidget* create_win_has_nest (void);
