#!/bin/sh

apt-get install -y texlive-extra-utils texlive-latex-recommended texlive-font-utils texlive-fonts-extra texlive-latex-extra texlive-fonts-recommended
# On a Devuan 3.1 Beowulf:
# apt-get install texlive-extra-utils texlive-fonts-extra texlive-latex-extra texlive-generic-extra
# On Ubuntu:
# apt-get install texlive-font-utils texlive-extra-utils texlive-fonts-extra texlive-latex-extra
