
                     ____
                    /\   \
   GNU/Linux live  /::\ D \      DYNE:BOLIC   AFRO LINUX   LIVE   BOOTABLE CD
     open source  /::::\ Y \               1 0 0 %  FREE SOFTWARE
  free software  /::::::\ N \     
   bootable CD  /:::/\:::\ E \     ver 2.4          .'~~~~~~~~~~~~~~~~~~~~~~'\
               /:::/@@\:::\ B \                     |                       | \
              /:::/@@@/\:::\ O \    codename        | boot menu:            |_/
 v. 2.4      /:::/@@@/  \:::\ L \        DHORUBA    |                       |
 forged in  /:::/@@@/____\:::\ I \                  | F1 - intro banner     |
 Amsterdam /:::/@@@/  (((i)))   C \  RASTA SOFTWARE |                       |
  6jun06  /:::/@@@/_____________   \  (C) 2001-2007 | F2 - boot options     |
         /::::\   \@@@@@@@@@@@@/\ G \  jaromil aka  | F3 - video modes      |
        /::::::\   \@@@@@@@@@@/::\ N \  Denis Rojo  | F4 - thin client      |
       /:::/\:::\   \    /:::/\:::\ U \             |                       |
      /:::/@@\:::\   \  /:::/@@\:::\ L \            | F5 - GNU GPL license  |
     /:::/@@@/\:::\   \/:::/@@@/\:::\ I \           |                       |
    /:::/@@@/  \:::\  /:::/@@@/  \:::\ N \          | press enter to accept | 
   /:::/@@@/____\:::\/:::/@@@/____\:::\ U \         |   the license & boot  |
  /:::/@@@/ dyne.org \::/@@@/   GNU GPL  X \     /~~~~~~~~~~~~~~~~~~~~~~~~/ |
 /:::/@@@/____________\/@@@/________________\    \________________________\/
 \::/@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@/
  \/@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@/

