
 This software is free software; you can redistribute it and/or
 modify it under the terms of the GNU Public License as published 
 by the Free Software Foundation; either version 2 of the License,
 or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 Please refer to the GNU Public License for more details.

 You should have received a copy of the GNU Public License along with
 this source code; if not, write to:
 Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA

 Going further with the boot process and using this CD-ROM, you
 accept the terms defined here and in the GNU Public License.

 Dynebolic is copyleft (C) 2001-2005 by Denis "jaromil" Rojo
 the included code is copyright by the respective authors, please
 refer to the distributed documentation for details.

