/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("dyne:bolic :: lost in babylon");
gchar *s = N_("Choose your language:");
gchar *s = N_("Choose your keyboard layout:");
gchar *s = N_("_Ok");
