/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("taschino :: nest your dyne:bolic");
gchar *s = N_("With a NEST you have the possibility to save your personal data and settings on HARDDISK or USB storage devices, to find them back the next time you run dyne:bolic.\n"
              "You don't need to change partitions, you just create a new file ( dynebol.nst ) of the size you choose.");
gchar *s = N_("nest on\n"
              "HARDDISK");
gchar *s = N_("Nest on\n"
              "USB KEY");
gchar *s = N_("You've got a home with");
gchar *s = N_("taschino :: about");
gchar *s = N_("The nesting function offered by dyne:bolic\n"
              "bla bla bla bla\n"
              "");
gchar *s = N_("OK, i got it");
gchar *s = N_("Know more about the dyne:bolic nesting and docking system");
gchar *s = N_("taschino :: nest on HARDDISK storage");
gchar *s = N_("Select the partition where\n"
              "you want to create the NEST");
gchar *s = N_("how many MEGABYTES should your nest occupy?");
gchar *s = N_("By securing you will generate an encrypted\n"
              "nest and you will need to set a passphrase\n"
              "20 characters long, to be used at every boot.");
gchar *s = N_("Nest your home and settings on  a harddisk partition");
gchar *s = N_("taschino :: nest on USB storage");
gchar *s = N_("no usb storage device found");
gchar *s = N_("how many MEGABYTES should your nest occupy?");
gchar *s = N_("By securing you will generate an encrypted\n"
              "nest and you will need to set a passphrase\n"
              "20 characters long, to be used at every boot.");
gchar *s = N_("Nest your home and settings on a usb storage key");
gchar *s = N_("taschino :: an error occurred!");
gchar *s = N_("a mysterious error occurred\n"
              "while processing :^(");
gchar *s = N_("Grrr !");
gchar *s = N_("ERROR");
gchar *s = N_("taschino :: success!");
gchar *s = N_("operation completed succesfully! :^)");
gchar *s = N_(" OK !");
