static char *credits_txt = 
"dyne:bolic 1.0 it is shaped on the needs of media activists\n"
"to stimulate the production and not only the fruition of digital\n"
"and analog informations.\n"
"It takes birth as a grassroot effort to spread free software\n"
"and the spirit of sharing informations.\n"
"\n"
"The following people also contributed to development:\n"
"  Lo Smilzo (hack to make it work on XBOX)\n"
"  Lobo (karma and knowledge)\n"
"  Sandolo and Rageman (scripts and tricks)\n"
"  Nightolo and Rubik (MuSE interface coders)\n"
"  Maox (logo and graphics)\n"
"  Eni and Newmark (watching horizons)\n"
"\n"
"Help with online documentation was given by: Isazi, Quique,\n"
"Ali Uelke, Thomas Hassan, Ricardo Perry, Marco Herrn,\n"
"Tommaso Gagliardi, Patrice.\n"
"\n"
"SUPPORT in development was given by the following\n"
"organizazions:\n"
"  TENOVIS (Intl) http://tenovis.com\n"
"  PUBLIC VOICE Lab (Vienna) http://pvl.at\n"
"  MALASystem (Milano) http://malasystem.com\n"
"  SERVUS.at (Linz) http://servus.at\n"
"  OSSA (Intl) http://streamingalliance.org\n"
"  Montevideo (Amsterdam) http://montevideo.nl\n"
"  Stream on the fly (EU project)\n"
//"  JuX project (Vienna) http://netbridge.at\n"
"  European Social Forum http://www.fse-esf.org\n"
"  The city of Firenze\n"
"and individuals:\n"
"  Stefano Chiccarelli, Roland Alton-Scheidl, Adam Hyde,\n"
"  Markus Panholzer, Zeljko Blace and Blicero\n"
"\n"
"Our waves and cheers also go to:\n"
"NeURo, Neural.it, cjm di enemy.org, Luca Lampo per la camicia :)\n"
"littlejohn, Odo grand visir di mufhd0, kobaiashi di sikurezza.org\n"
"Tommaso aka m_0, Dolce, chmod, radio Ondarossa, enuzzo, void,\n"
"Dindon il carbonaro, #mdp and all the hackers at dyne.org.\n"
"\n"
"This CD includes the work of hundreds of people all around\n"
"the world developing free software and GNU/Linux applications,\n"
"without the efforts of this big communities dyne:bolic would\n"
"have never existed, among the others are gnu.org and the\n"
"Free Software Foundation, gentoo.org, kernel.org, xfree86.org,\n"
"mozilla.org.\n"
"\n"
"You are welcome to join us!\n"
"the dyne:bolic mailinglist you can reach from dynebolic.org\n"
"the irc channel #dynebolic on irc.autistici.org\n"
"\n"
"happy hacking ;^)";

