/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Welcome to dyne:bolic");
gchar *s = N_("DYNE.ORG PRODUCTIONS PRESENTS");
gchar *s = N_("WELCOME TO THE FREE MULTIMEDIA OPERATING SYSTEM\n"
              "PRESS RIGHT MOUSE BUTTON ON THE DESKTOP FOR THE MENU");
gchar *s = N_("It's hacktive!");
gchar *s = N_("\n"
              "Dyne:bolic is a GNU/Linux operating system automatically recognizing your hardware.\n"
              "\n"
              "Your /home directory resides in your RAM memory and everything will disappear without the CD.\n"
              "\n"
              "You can dock the system in your harddisk by copying the /dyne directory into it: no installation needed!\n"
              "\n"
              "You can save and retrieve your settings by creating a nest file on your usb key or harddisk.\n"
              "\n"
              "You are root and have access to all your harddisks.\n"
              "\n"
              "Switch desktop alt+2,3... get menu with right click  ;^)");
gchar *s = N_("Language");
gchar *s = N_("Network");
gchar *s = N_("Modem");
gchar *s = N_("Printer");
gchar *s = N_("Screen");
gchar *s = N_("Nest !");
gchar *s = N_("CONFIGURE");
gchar *s = N_("Getting started");
gchar *s = N_("\n"
              "The dyne:bolic developers are freelancers available to provide help with workshops, customisations, setup of medialabs, consulting, art publications and warranty to\n"
              "fit this software for particular purposes.\n"
              "\n"
              "On the dynebolic.org website, see the Customize and Workshop sections.\n"
              "\n"
              "See the dyne.org website and join the mailinglist community to know more about\n"
              "the hackers involved and how to contact them.\n"
              "");
gchar *s = N_("dyne:bolic is an\n"
              "operating system\n"
              "mantained with\n"
              "artisanal dedication\n"
              "and passion;\n"
              "please express\n"
              "your appreciation");
gchar *s = N_("with a kind offer");
gchar *s = N_("share with solidarity");
gchar *s = N_("Support");
gchar *s = N_("http://rastasoft.org");
gchar *s = N_("freedom of creation");
gchar *s = N_("MORE ON DYNEBOLIC.ORG");
gchar *s = N_("    HIGH PAWA        ::        BIG UP \\o/    ");
gchar *s = N_("Credits");
gchar *s = N_("Unhauthorized copying, distribution and public exhibition of this media and broadcasting from it is encouraged! 100% free ;^)");
gchar *s = N_("GNU GENERAL PUBLIC LICENSE  Version 2, June 1991\n"
              "dyne:bolic is free software; you can redistribute it and/or modify it under\n"
              "the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option)\n"
              "any later version.\n"
              "dyne:bolic is distributed in the hope that it will be useful, but WITHOUT\n"
              "ANY WARRANTY; without even the implied warranty of MERCHANTABILITY\n"
              "or FITNESS FOR A PARTICULAR PURPOSE. Please refer to the GNU General Public License for more details.\n"
              "You should have received a copy of the GNU General Public License\n"
              "along with dyne:bolic; if not, write to: Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.");
gchar *s = N_("dyne:bolic is copyleft (c)2001-2005 by Denis \"jaromil\" Rojo\n"
              "Several redistributed binaries are copyrighted by the respective authors, refer to documentation and manual pages for details.\n"
              "The source of all included binaries is available upon request, it's all GNU GPL license and, in some cases, X/BSD/Mozilla/MIT.");
gchar *s = N_("License");
