#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

if grep all_generic_ide /proc/cmdline 2>/dev/null; then
	modprobe ata_generic all_generic_ide=1
fi
