/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("nettante :: dyne:bolic network configuration");
gchar *s = N_("Setup the network for your dyne:bolic system.\n"
              "\n"
              "Choose a network card and how to configure it:\n"
              "DHCP auto configuration or manually assigned STATIC IP.");
gchar *s = N_("DHCP");
gchar *s = N_("Static IP");
gchar *s = N_("Your hostname on the net:");
gchar *s = N_("Confirm your settings:");
gchar *s = N_("apply your settings");
gchar *s = N_("Apply");
gchar *s = N_("save settings in your nest");
gchar *s = N_("Save");
gchar *s = N_("Quit");
gchar *s = N_("nettante :: static IP configuration");
gchar *s = N_("Fill in your manual settings; if you don't know them you should discover more about the network you want to connect! maybe ask somebody that knows more? or go back and try the DHCP automatic configuration.");
gchar *s = N_("Your numerical IP address:");
gchar *s = N_("probably something like 192.168.0.69");
gchar *s = N_("Netmask:");
gchar *s = N_("255.255.255.0");
gchar *s = N_("Gateway to external networks:");
gchar *s = N_("probably something like 192.168.0.1");
gchar *s = N_("Domain Name Server:");
gchar *s = N_("if you don't have one, try 195.34.133.10");
gchar *s = N_("Abort");
gchar *s = N_("apply settings and save them!");
gchar *s = N_("OK!");
