/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_win_main (void)
{
  GtkWidget *win_main;
  GtkWidget *vbox1;
  GtkWidget *hbox1;
  GtkWidget *intro_label;
  GtkWidget *dynetux;
  GtkWidget *hbox7;
  GtkWidget *check_active;
  GtkWidget *combo_eth;
  GtkWidget *eth_choice;
  GtkWidget *hbox6;
  GtkWidget *toggle_dhcp;
  GtkWidget *toggle_staticip;
  GtkWidget *vbox7;
  GtkWidget *label_hostname;
  GtkWidget *entry_staticip_hostname;
  GtkWidget *hbox5;
  GtkWidget *label_confirm;
  GtkWidget *hbuttonbox2;
  GtkWidget *button_main_apply;
  GtkWidget *button_main_save;
  GtkWidget *button_main_quit;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_main, "win_main");
  gtk_object_set_data (GTK_OBJECT (win_main), "win_main", win_main);
  gtk_window_set_title (GTK_WINDOW (win_main), _("nettante :: dyne:bolic network configuration"));
  gtk_window_set_position (GTK_WINDOW (win_main), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (win_main), FALSE, FALSE, FALSE);
  gtk_window_set_wmclass (GTK_WINDOW (win_main), "nettante", "dynebolic");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (win_main), vbox1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  intro_label = gtk_label_new (_("Setup the network for your dyne:bolic system.\n\nChoose a network card and how to configure it:\nDHCP auto configuration or manually assigned STATIC IP."));
  gtk_widget_set_name (intro_label, "intro_label");
  gtk_widget_ref (intro_label);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "intro_label", intro_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (intro_label);
  gtk_box_pack_start (GTK_BOX (hbox1), intro_label, TRUE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (intro_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (intro_label), 0, 5);

  dynetux = create_pixmap (win_main, "dynetux.xpm");
  gtk_widget_set_name (dynetux, "dynetux");
  gtk_widget_ref (dynetux);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "dynetux", dynetux,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dynetux);
  gtk_box_pack_start (GTK_BOX (hbox1), dynetux, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (dynetux), 0, 3);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox7, "hbox7");
  gtk_widget_ref (hbox7);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "hbox7", hbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox7, FALSE, FALSE, 0);

  check_active = gtk_check_button_new_with_label ("");
  gtk_widget_set_name (check_active, "check_active");
  gtk_widget_ref (check_active);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "check_active", check_active,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (check_active);
  gtk_box_pack_start (GTK_BOX (hbox7), check_active, FALSE, FALSE, 0);

  combo_eth = gtk_combo_new ();
  gtk_widget_set_name (combo_eth, "combo_eth");
  gtk_widget_ref (combo_eth);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "combo_eth", combo_eth,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_eth);
  gtk_box_pack_start (GTK_BOX (hbox7), combo_eth, TRUE, TRUE, 0);
  gtk_widget_set_usize (combo_eth, 400, -2);
  gtk_container_set_border_width (GTK_CONTAINER (combo_eth), 5);

  eth_choice = GTK_COMBO (combo_eth)->entry;
  gtk_widget_set_name (eth_choice, "eth_choice");
  gtk_widget_ref (eth_choice);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "eth_choice", eth_choice,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (eth_choice);

  hbox6 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox6, "hbox6");
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox6, FALSE, FALSE, 0);

  toggle_dhcp = gtk_toggle_button_new_with_label (_("DHCP"));
  gtk_widget_set_name (toggle_dhcp, "toggle_dhcp");
  gtk_widget_ref (toggle_dhcp);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "toggle_dhcp", toggle_dhcp,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toggle_dhcp);
  gtk_box_pack_start (GTK_BOX (hbox6), toggle_dhcp, FALSE, FALSE, 0);

  toggle_staticip = gtk_toggle_button_new_with_label (_("Static IP"));
  gtk_widget_set_name (toggle_staticip, "toggle_staticip");
  gtk_widget_ref (toggle_staticip);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "toggle_staticip", toggle_staticip,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toggle_staticip);
  gtk_box_pack_start (GTK_BOX (hbox6), toggle_staticip, FALSE, FALSE, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox7, "vbox7");
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox7, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox7), 10);

  label_hostname = gtk_label_new (_("Your hostname on the net:"));
  gtk_widget_set_name (label_hostname, "label_hostname");
  gtk_widget_ref (label_hostname);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "label_hostname", label_hostname,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_hostname);
  gtk_box_pack_start (GTK_BOX (vbox7), label_hostname, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_hostname), GTK_JUSTIFY_LEFT);

  entry_staticip_hostname = gtk_entry_new ();
  gtk_widget_set_name (entry_staticip_hostname, "entry_staticip_hostname");
  gtk_widget_ref (entry_staticip_hostname);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "entry_staticip_hostname", entry_staticip_hostname,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_staticip_hostname);
  gtk_box_pack_start (GTK_BOX (vbox7), entry_staticip_hostname, FALSE, FALSE, 0);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox5, TRUE, TRUE, 0);

  label_confirm = gtk_label_new (_("Confirm your settings:"));
  gtk_widget_set_name (label_confirm, "label_confirm");
  gtk_widget_ref (label_confirm);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "label_confirm", label_confirm,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_confirm);
  gtk_box_pack_start (GTK_BOX (hbox5), label_confirm, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_confirm), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (label_confirm), 10, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox2, "hbuttonbox2");
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (hbox5), hbuttonbox2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox2), 1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox2), 5);

  button_main_apply = gtk_button_new_with_label (_("Apply"));
  gtk_widget_set_name (button_main_apply, "button_main_apply");
  gtk_widget_ref (button_main_apply);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "button_main_apply", button_main_apply,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_main_apply);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button_main_apply);
  GTK_WIDGET_SET_FLAGS (button_main_apply, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_main_apply, _("apply your settings"), NULL);

  button_main_save = gtk_button_new_with_label (_("Save"));
  gtk_widget_set_name (button_main_save, "button_main_save");
  gtk_widget_ref (button_main_save);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "button_main_save", button_main_save,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_main_save);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button_main_save);
  GTK_WIDGET_SET_FLAGS (button_main_save, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_main_save, _("save settings in your nest"), NULL);

  button_main_quit = gtk_button_new_with_label (_("Quit"));
  gtk_widget_set_name (button_main_quit, "button_main_quit");
  gtk_widget_ref (button_main_quit);
  gtk_object_set_data_full (GTK_OBJECT (win_main), "button_main_quit", button_main_quit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_main_quit);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button_main_quit);
  GTK_WIDGET_SET_FLAGS (button_main_quit, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (win_main), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (check_active), "realize",
                      GTK_SIGNAL_FUNC (on_check_active_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (check_active), "pressed",
                      GTK_SIGNAL_FUNC (on_check_active_pressed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (combo_eth), "realize",
                      GTK_SIGNAL_FUNC (on_combo_eth_realize),
                      combo_eth);
  gtk_signal_connect (GTK_OBJECT (eth_choice), "changed",
                      GTK_SIGNAL_FUNC (on_eth_choice_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toggle_dhcp), "realize",
                      GTK_SIGNAL_FUNC (on_toggle_dhcp_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toggle_dhcp), "released",
                      GTK_SIGNAL_FUNC (on_toggle_dhcp_released),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toggle_staticip), "released",
                      GTK_SIGNAL_FUNC (on_toggle_staticip_released),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toggle_staticip), "realize",
                      GTK_SIGNAL_FUNC (on_toggle_staticip_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry_staticip_hostname), "realize",
                      GTK_SIGNAL_FUNC (on_entry_hostname_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_main_apply), "released",
                      GTK_SIGNAL_FUNC (on_button_main_apply_released),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_main_save), "released",
                      GTK_SIGNAL_FUNC (on_button_main_save_released),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button_main_quit), "released",
                      GTK_SIGNAL_FUNC (on_button_main_quit_released),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (win_main), "tooltips", tooltips);

  return win_main;
}

GtkWidget*
create_win_staticip (void)
{
  GtkWidget *win_staticip;
  GtkWidget *vbox2;
  GtkWidget *hbox2;
  GtkWidget *label_staticip;
  GtkWidget *pixmap_staticip;
  GtkWidget *hbox3;
  GtkWidget *vbox3;
  GtkWidget *label_staticip_yourip;
  GtkWidget *entry_staticip_address;
  GtkWidget *vbox4;
  GtkWidget *label_staticip_netmask;
  GtkWidget *entry_staticip_netmask;
  GtkWidget *hbox4;
  GtkWidget *vbox5;
  GtkWidget *label_staticip_gw;
  GtkWidget *entry_staticip_gw;
  GtkWidget *vbox6;
  GtkWidget *label_staticip_dns;
  GtkWidget *entry_staticip_dns;
  GtkWidget *hbuttonbox_staticip;
  GtkWidget *button_staticip_abort;
  GtkWidget *button_staticip_ok;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_staticip = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (win_staticip, "win_staticip");
  gtk_object_set_data (GTK_OBJECT (win_staticip), "win_staticip", win_staticip);
  gtk_container_set_border_width (GTK_CONTAINER (win_staticip), 10);
  gtk_window_set_title (GTK_WINDOW (win_staticip), _("nettante :: static IP configuration"));
  gtk_window_set_position (GTK_WINDOW (win_staticip), GTK_WIN_POS_MOUSE);
  gtk_window_set_policy (GTK_WINDOW (win_staticip), FALSE, FALSE, FALSE);
  gtk_window_set_wmclass (GTK_WINDOW (win_staticip), "nettante", "dynebolic");

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (win_staticip), vbox2);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox2, TRUE, TRUE, 0);

  label_staticip = gtk_label_new (_("Fill in your manual settings; if you don't know them you should discover more about the network you want to connect! maybe ask somebody that knows more? or go back and try the DHCP automatic configuration."));
  gtk_widget_set_name (label_staticip, "label_staticip");
  gtk_widget_ref (label_staticip);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "label_staticip", label_staticip,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_staticip);
  gtk_box_pack_start (GTK_BOX (hbox2), label_staticip, TRUE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_staticip), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label_staticip), TRUE);
  gtk_misc_set_padding (GTK_MISC (label_staticip), 5, 0);

  pixmap_staticip = create_pixmap (win_staticip, "staticip.xpm");
  gtk_widget_set_name (pixmap_staticip, "pixmap_staticip");
  gtk_widget_ref (pixmap_staticip);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "pixmap_staticip", pixmap_staticip,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap_staticip);
  gtk_box_pack_start (GTK_BOX (hbox2), pixmap_staticip, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (pixmap_staticip), 5, 0);

  hbox3 = gtk_hbox_new (TRUE, 20);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox3, TRUE, TRUE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 5);

  label_staticip_yourip = gtk_label_new (_("Your numerical IP address:"));
  gtk_widget_set_name (label_staticip_yourip, "label_staticip_yourip");
  gtk_widget_ref (label_staticip_yourip);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "label_staticip_yourip", label_staticip_yourip,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_staticip_yourip);
  gtk_box_pack_start (GTK_BOX (vbox3), label_staticip_yourip, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label_staticip_yourip), 0, 2);

  entry_staticip_address = gtk_entry_new_with_max_length (16);
  gtk_widget_set_name (entry_staticip_address, "entry_staticip_address");
  gtk_widget_ref (entry_staticip_address);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "entry_staticip_address", entry_staticip_address,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_staticip_address);
  gtk_box_pack_start (GTK_BOX (vbox3), entry_staticip_address, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, entry_staticip_address, _("probably something like 192.168.0.69"), NULL);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox4, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 5);

  label_staticip_netmask = gtk_label_new (_("Netmask:"));
  gtk_widget_set_name (label_staticip_netmask, "label_staticip_netmask");
  gtk_widget_ref (label_staticip_netmask);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "label_staticip_netmask", label_staticip_netmask,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_staticip_netmask);
  gtk_box_pack_start (GTK_BOX (vbox4), label_staticip_netmask, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label_staticip_netmask), 0, 2);

  entry_staticip_netmask = gtk_entry_new_with_max_length (16);
  gtk_widget_set_name (entry_staticip_netmask, "entry_staticip_netmask");
  gtk_widget_ref (entry_staticip_netmask);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "entry_staticip_netmask", entry_staticip_netmask,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_staticip_netmask);
  gtk_box_pack_start (GTK_BOX (vbox4), entry_staticip_netmask, FALSE, FALSE, 0);
  gtk_entry_set_text (GTK_ENTRY (entry_staticip_netmask), _("255.255.255.0"));

  hbox4 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox4, TRUE, TRUE, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox5, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox5), 5);

  label_staticip_gw = gtk_label_new (_("Gateway to external networks:"));
  gtk_widget_set_name (label_staticip_gw, "label_staticip_gw");
  gtk_widget_ref (label_staticip_gw);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "label_staticip_gw", label_staticip_gw,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_staticip_gw);
  gtk_box_pack_start (GTK_BOX (vbox5), label_staticip_gw, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label_staticip_gw), 0, 2);

  entry_staticip_gw = gtk_entry_new_with_max_length (16);
  gtk_widget_set_name (entry_staticip_gw, "entry_staticip_gw");
  gtk_widget_ref (entry_staticip_gw);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "entry_staticip_gw", entry_staticip_gw,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_staticip_gw);
  gtk_box_pack_start (GTK_BOX (vbox5), entry_staticip_gw, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, entry_staticip_gw, _("probably something like 192.168.0.1"), NULL);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox6, "vbox6");
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox6, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox6), 5);

  label_staticip_dns = gtk_label_new (_("Domain Name Server:"));
  gtk_widget_set_name (label_staticip_dns, "label_staticip_dns");
  gtk_widget_ref (label_staticip_dns);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "label_staticip_dns", label_staticip_dns,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_staticip_dns);
  gtk_box_pack_start (GTK_BOX (vbox6), label_staticip_dns, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label_staticip_dns), 0, 2);

  entry_staticip_dns = gtk_entry_new ();
  gtk_widget_set_name (entry_staticip_dns, "entry_staticip_dns");
  gtk_widget_ref (entry_staticip_dns);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "entry_staticip_dns", entry_staticip_dns,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry_staticip_dns);
  gtk_box_pack_start (GTK_BOX (vbox6), entry_staticip_dns, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, entry_staticip_dns, _("if you don't have one, try 195.34.133.10"), NULL);

  hbuttonbox_staticip = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox_staticip, "hbuttonbox_staticip");
  gtk_widget_ref (hbuttonbox_staticip);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "hbuttonbox_staticip", hbuttonbox_staticip,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox_staticip);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox_staticip, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox_staticip), 5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox_staticip), GTK_BUTTONBOX_SPREAD);

  button_staticip_abort = gtk_button_new_with_label (_("Abort"));
  gtk_widget_set_name (button_staticip_abort, "button_staticip_abort");
  gtk_widget_ref (button_staticip_abort);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "button_staticip_abort", button_staticip_abort,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_staticip_abort);
  gtk_container_add (GTK_CONTAINER (hbuttonbox_staticip), button_staticip_abort);
  GTK_WIDGET_UNSET_FLAGS (button_staticip_abort, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (button_staticip_abort, GTK_CAN_DEFAULT);

  button_staticip_ok = gtk_button_new_with_label (_("OK!"));
  gtk_widget_set_name (button_staticip_ok, "button_staticip_ok");
  gtk_widget_ref (button_staticip_ok);
  gtk_object_set_data_full (GTK_OBJECT (win_staticip), "button_staticip_ok", button_staticip_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button_staticip_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox_staticip), button_staticip_ok);
  GTK_WIDGET_UNSET_FLAGS (button_staticip_ok, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (button_staticip_ok, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_staticip_ok, _("apply settings and save them!"), NULL);

  gtk_signal_connect (GTK_OBJECT (win_staticip), "destroy",
                      GTK_SIGNAL_FUNC (on_win_staticip_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry_staticip_address), "realize",
                      GTK_SIGNAL_FUNC (on_entry_staticip_address_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry_staticip_netmask), "realize",
                      GTK_SIGNAL_FUNC (on_entry_staticip_netmask_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry_staticip_gw), "realize",
                      GTK_SIGNAL_FUNC (on_entry_staticip_gw_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (entry_staticip_dns), "realize",
                      GTK_SIGNAL_FUNC (on_entry_staticip_dns_realize),
                      NULL);
  gtk_signal_connect_object (GTK_OBJECT (button_staticip_abort), "released",
                             GTK_SIGNAL_FUNC (gtk_widget_destroy),
                             GTK_OBJECT (win_staticip));
  gtk_signal_connect (GTK_OBJECT (button_staticip_ok), "released",
                      GTK_SIGNAL_FUNC (on_button_staticip_ok_released),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (win_staticip), "tooltips", tooltips);

  return win_staticip;
}

